
services:
  web:
    image: 'nginx:1.23.4-alpine'
    ports:
      - '8080:80'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php
    
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/var/www/html'
