services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
    working_dir: /var/www/symfony
    networks:
      - symfony-net

  nginx:
    image: nginx:1.28.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony-net

networks:
  symfony-net:
    driver: bridge
